version: '3.8'
services:

  nginx:
    image: nginx:1.21.6-alpine
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    depends_on:
      - front
      - back

  front:
    build: { context: ./front, target : dev }
    volumes:
      - ./front:/app
    expose:
      - 3000
    ports:
      - 35729:35729  # for livereload
    depends_on:
      - back
    stdin_open: true # docker run -i
    tty       : true # docker run -t
    command: sh -c "yarn install && yarn start"

  back:
    build: { context: ./back, target: dev }
    volumes:
      - ./back:/app
    expose:
      - 8000
    depends_on:
      - db
    stdin_open: true  # docker run -i
    tty       : true  # docker run -t
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env

  db:
    build: { context: ./db }
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    
  
volumes:
  db:
