# Generated by Django 4.2.2 on 2024-02-18 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('no_traffic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streetinintersection',
            name='intersection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streetsInIntersection', to='no_traffic.intersection'),
        ),
    ]
